name: CI

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 18.x
      uses: actions/setup-node@v4
      with:
        node-version: 18.x
        cache: 'pnpm'
    - name: Get npm global bin path and add to PATH
      run: echo "$(npm config get prefix)/bin" >> $GITHUB_PATH
    - name: Install pnpm
      run: npm install -g pnpm
    - name: Install dependencies
      run: pnpm install --no-frozen-lockfile
    - name: Run tests
      run: pnpm test
    - name: Run linter
      run: pnpm run lint
